// <auto-generated />
namespace Terminal.Data.Config
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class numcontaadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(numcontaadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241718510_numcontaadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
